load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "interpolation",
    srcs = [
    "interp.hpp",
    "interp.cpp",
    "interpolate_vector.cpp",
    "interpolate_vector.h",
    ],
    visibility = ["//main:__pkg__"],
)
