load("@rules_cc//cc:defs.bzl", "cc_library")

cc_library(
    name = "utils",
    hdrs = ["geometric_transformations.h"],
    srcs = ["geometric_transformations.cpp"],
    visibility = ["//visibility:public"],
        deps = [
        "//object_tracking/data_types:data_types",
    ],
)
